name: Deploy Next.js Site to GitHub Pages

on:
  push:
    branches:
      - main  # or whichever branch should trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ensure this matches the version you use locally

      - name: Install dependencies
        run: npm install

      - name: Build and export
        run: npm run build  # This should create the `out` folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: prod  # Branch to deploy to
          publish_dir: ./out  # Directory to deploy from
          keep_files: false  # Set to true if you want to keep previous builds
