name: Deploy Next.js Site to GitHub Pages

on:
  push:
    branches: ["main"]  # This specifies that the workflow runs on pushes to the main branch.
  workflow_dispatch:    # Allows you to manually trigger the workflow from the GitHub UI.

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out the repository content into the GitHub Actions runner.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'  # Make sure to use the node version that matches your project requirements.
          cache: 'npm'            # Caches npm modules for faster subsequent builds.

      - name: Install dependencies
        run: npm ci  # Installs project dependencies based on the lock file.

      - name: Build with Next.js
        run: npm run build  # Builds the Next.js project, outputting static files to the 'out' directory.

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.1  # Deploys the build output to GitHub Pages.
        with:
          branch: prod  # The branch you want to deploy to.
          folder: out   # The folder where your build outputs the static files.
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # The Personal Access Token you set in your repository secrets.
